#ifndef DefineKeys_h_
#define DefineKeys_h_

/// AROW KEYS
#define LEFT_ARROW_KEY SDLK_LEFT
#define RIGHT_ARROW_KEY SDLK_RIGHT
#define UP_ARROW_KEY SDLK_UP
#define DOWN_ARROW_KEY SDLK_DOWN

/// LETTERS
#define Q_KEY SDLK_q
#define W_KEY SDLK_w
#define E_KEY SDLK_e
#define R_KEY SDLK_r
#define T_KEY SDLK_t
#define Y_KEY SDLK_y
#define U_KEY SDLK_u
#define I_KEY SDLK_i
#define O_KEY SDLK_o
#define P_KEY SDLK_p
#define A_KEY SDLK_a
#define S_KEY SDLK_s
#define D_KEY SDLK_d
#define F_KEY SDLK_f
#define G_KEY SDLK_g
#define H_KEY SDLK_h
#define J_KEY SDLK_j
#define K_KEY SDLK_k
#define L_KEY SDLK_l
#define Z_KEY SDLK_z
#define X_KEY SDLK_x
#define C_KEY SDLK_c
#define V_KEY SDLK_v
#define B_KEY SDLK_b
#define N_KEY SDLK_n
#define M_KEY SDLK_m

/// MISC
#define ESCAPE_KEY SDLK_ESCAPE
#define SPACE_KEY SDLK_SPACE
#define SHIFT_KEY SDLK_LSHIFT
#define ENTER_KEY SDLK_RETURN

/// MOUSE BUTTONS
#define LEFT_MOUSE_BUTTON SDL_BUTTON_LEFT
#define MIDDLE_MOUSE_BUTTON SDL_BUTTON_MIDDLE
#define RIGHT_MOUSE_BUTTON SDL_BUTTON_RIGHT



// CONTROLLER BUTTONS 
#define X_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_X
#define Y_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_Y
#define A_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_A
#define B_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_B

#define UP_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_DPAD_UP
#define DOWN_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_DPAD_DOWN
#define LEFT_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_DPAD_LEFT
#define RIGHT_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_DPAD_RIGHT

#define START_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_START

#define RT_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_RIGHTSHOULDER
#define LT_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_LEFTSHOULDER

#define RIGHT_STICK_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_RIGHTSTICK
#define LEFT_STICK_CONTROLLER SDL_GameControllerButton::SDL_CONTROLLER_BUTTON_LEFTSTICK

#endif