#ifndef DefineKeys_h_
#define DefineKeys_h_

/// AROW KEYS
#define LEFT_ARROW_KEY SDLK_LEFT
#define RIGHT_ARROW_KEY SDLK_RIGHT
#define UP_ARROW_KEY SDLK_UP
#define DOWN_ARROW_KEY SDLK_DOWN

/// LETTERS
#define W_KEY SDLK_w
#define A_KEY SDLK_a
#define S_KEY SDLK_s
#define D_KEY SDLK_d

/// MISC
#define ESCAPE_KEY SDLK_ESCAPE
#define SPACE_KEY SDLK_SPACE
#define SHIFT_KEY SDLK_LSHIFT
#define ENTER_KEY SDLK_RETURN

/// MOUSE BUTTONS
#define LEFT_MOUSE_BUTTON SDL_BUTTON_LEFT
#define MIDDLE_MOUSE_BUTTON SDL_BUTTON_MIDDLE
#define RIGHT_MOUSE_BUTTON SDL_BUTTON_RIGHT

#endif